# coordinator messages
VOTE_REQUEST = "VOTE_REQUEST"
PREPARE_COMMIT = "PREPARE_COMMIT" 
GLOBAL_COMMIT = "GLOBAL_COMMIT"
GLOBAL_ABORT = "GLOBAL_ABORT"

# participant messages
VOTE_COMMIT = "VOTE_COMMIT"
VOTE_ABORT = "VOTE_ABORT"
READY_COMMIT = "READY_COMMIT"
NEED_DECISION = "NEED_DECISION"
STATE_REQUEST = "STATE_REQUEST" 
STATE_RESPONSE = "STATE_RESPONSE"

# participant decisions
LOCAL_SUCCESS = "LOCAL_SUCCESS"
LOCAL_ABORT = "LOCAL_ABORT"

# states
INIT = "INIT"
WAIT = "WAIT"
READY = "READY"
PRECOMMIT = "PRECOMMIT"
COMMIT = "COMMIT" 
ABORT = "ABORT"

# misc
TIMEOUT = 2.0 